### PR TITLE
Dev legacy

### PR DESCRIPTION
**Pull request by sakithb**
changes in review (https://github.com/users/sakithb/projects/2) for v27

### CODE REVIEW

**Comment by sakithb** [comment]
> @sakithb the changes for #59 are not there. You also changed some translation relevant stuff which needs to be updated

I missed them. Let me see again. Can you handle the translation stuff?

**Comment by ChrisLauinger77** [comment]
sure I update the file in the evening - I am @work currently

**Comment by sakithb** [comment]
Sure, ofc

**Comment by ChrisLauinger77** [comment]
I added the stuff for #59

**Comment by sakithb** [comment]
Thanks. We will not be doing work gnome44 besides bug fixes anyway

**Pull request merged**
