### PR TITLE
Added seek slider

### PR DESCRIPTION
**Pull request by sakithb**
Fix for #33

### CODE REVIEW

**Comment by sakithb** [comment]
Should be ported for gnome 45/v26

**Comment by ChrisLauinger77** [comment]
main would be v28 next release - I can do the porting / testing on gnome OS

**Comment by sakithb** [comment]
> main would be v28 next release - I can do the porting / testing on gnome OS

For gnome 44 it's v27 right

**Comment by ChrisLauinger77** [comment]
yes gnome44 branch has 27 in metadata and is not released yet

**Comment by ChrisLauinger77** [comment]
netflix
netflix
youtube
youtube
spotify
spotify

only spotify looks OK - and I do not see the slider only the time counts.

**Comment by sakithb** [comment]
image
image
Weird. it looks fine for me. What theme are you using?

**Comment by ChrisLauinger77** [comment]
Custom accent colors theme - but it looks the same when I use the default one

**Comment by sakithb** [comment]
judging from the left padding in the popup, you are seem to be not using the code in the dev-legacy branch. I fixed the padding issues, in this merge request as well

**Comment by ChrisLauinger77** [comment]
yes I use the seek-ft - do not see the dev-legacy ?!

**Comment by sakithb** [comment]
> yes I use the seek-ft - do not see the dev-legacy ?!

seek-ft was merged with dev-legacy, can you try pulling again

**Comment by ChrisLauinger77** [comment]
yes - needed to fetch origin .  now I test again

**Comment by ChrisLauinger77** [comment]
Spotify looks better now
Bildschirmfoto vom 2023-10-17 20-26-57

But youtube and netflix not
Bildschirmfoto vom 2023-10-17 20-27-42

Bildschirmfoto vom 2023-10-17 20-28-06

**Comment by ChrisLauinger77** [comment]
Also 
Ignoring length property that isn't a number at line 21, col 17
Ignoring length property that isn't a number at line 22, col 18
Ignoring length property that isn't a number at line 1, col 13
Ignoring length property that isn't a number at line 1, col 32
Ignoring length property that isn't a number at line 21, col 17
Ignoring length property that isn't a number at line 22, col 18

this log messages are back which I fixed already - they come from 
margin: 0px auto;  the auto is not supported I believe

**Comment by sakithb** [comment]
It's not working properly on firefox, only chromium based browsers. Ill look into it more. Regarding the logs did you fix them in the gnome 44 branch as well?

**Comment by ChrisLauinger77** [comment]
I think I need to rebase gnome44 onto dev-legacy.

**Comment by ChrisLauinger77** [comment]
> It's not working properly on firefox, only chromium based browsers. Ill look into it more. Regarding the logs did you fix them in the gnome 44 branch as well?

yes but after you branched - I rebase and push - just a sec

**Comment by ChrisLauinger77** [comment]
After rebase its fine and also the fixes from gnome44 are in dev-legacy. logs looks good now.
Wanna investigate and fix firefox before the PR is done ?

**Comment by sakithb** [comment]
> After rebase its fine and also the fixes from gnome44 are in dev-legacy. logs looks good now. Wanna investigate and fix firefox before the PR is done ?

Thanks! I am working on fixing firefox. Actually it cannot be fixed because firefox does not expose the position information for any media playing, I guess we'll just have to hide the slider and the timestamps?

**Comment by ChrisLauinger77** [comment]
confirm chromium also works for me
Bildschirmfoto vom 2023-10-17 20-44-05

**Comment by ChrisLauinger77** [comment]
Yes just hide it when its not supported - spares us new issues :)

**Comment by sakithb** [comment]
I agree

**Comment by ChrisLauinger77** [comment]
Good job BTW - I like it very much

**Comment by sakithb** [comment]
Thanks!

> Good job BTW - I like it very much

I pushed the changes

**Comment by ChrisLauinger77** [comment]
Branch merged and cleaned - I will port the changes to main

**Pull request merged**
