### PR TITLE
Do not destroy objects on disable

### LINKED ISSUE #102: Multiple-delete causes GNOME 45 Shell segmentation fault
I'm using GNOME Shell 45.0 with Mutter 45 API13, from the Arch Linux repository.

When unlocking the session and adding/removing a MPRIS player, the entire session crashes, leaving behind these logs:

[gs-log.txt](https://github.com/sakithb/media-controls/files/13192957/gs-log.txt)
[gnome-shell-coredump.split.zip](https://github.com/sakithb/media-controls/files/13191053/gnome-shell-coredump.split.zip)
[gnome-shell-coredump.split.z01](https://github.com/sakithb/media-controls/files/13191056/gnome-shell-coredump.split01.zip)
[gnome-shell-coredump.split.z02](https://github.com/sakithb/media-controls/files/13191058/gnome-shell-coredump.split02.zip)

### PR DESCRIPTION
**Pull request by Thesola10**
This fixes #102

### CODE REVIEW

**Comment by Thesola10** [comment]
Ideally, the actual fix would be to decouple `disable()` and `enable()`f from the `Widget` instance entirely -- I'm surprised the crash never occurred before, all things considered.

**Comment by Thesola10** [comment]
Okay, the empty spaces are Player objects that are somehow not displayed as children of the Widget. Refreshing visibility should do the trick

**Comment by sakithb** [comment]
I cannot seem to recreate the graphical bug, can someone else confirm if you can recreate the graphical bug

**Comment by sakithb** [comment]
Can someone confirm if the graphical bug is fixed?

**Comment by ChrisLauinger77** [comment]
I just got gnome-shell and mutter updated to 45.1 in debian. and I cannot reproduce it any more.

**Comment by sakithb** [comment]
> I just got gnome-shell and mutter updated to 45.1 in debian. and I cannot reproduce it any more.

Thanks, I think we should be safe to merge this to main

**Comment by ChrisLauinger77** [comment]
> > I just got gnome-shell and mutter updated to 45.1 in debian. and I cannot reproduce it any more.
> 
> Thanks, I think we should be safe to merge this to main

No U got me wrong. Without this change it is not crashing for me any more. Looks like fixed in mutter / gnome-shell not in the extension

**Comment by sakithb** [comment]
> I just got gnome-shell and mutter updated to 45.1 in debian. and I cannot reproduce it any more.

Thanks, I think we should be safe to merge this to main

> > > I just got gnome-shell and mutter updated to 45.1 in debian. and I cannot reproduce it any more.
> > 
> > 
> > Thanks, I think we should be safe to merge this to main
> 
> No U got me wrong. Without this change it is not crashing for me any more. Looks like fixed in mutter / gnome-shell not in the extension

I am using gnome-shell and mutter 45.1 on fedora 39 and it is still crashing for me

**Comment by ChrisLauinger77** [comment]
> > I just got gnome-shell and mutter updated to 45.1 in debian. and I cannot reproduce it any more.
> 
> Thanks, I think we should be safe to merge this to main
> 
> > > > I just got gnome-shell and mutter updated to 45.1 in debian. and I cannot reproduce it any more.
> > > 
> > > 
> > > Thanks, I think we should be safe to merge this to main
> > 
> > 
> > No U got me wrong. Without this change it is not crashing for me any more. Looks like fixed in mutter / gnome-shell not in the extension
> 
> I am using gnome-shell and mutter 45.1 on fedora 39, and it is still crashing for me However, with the changes on this pr, it does not crash for me

Intresting  - but sure when it works and its better solution then before - why not merge it ...

**Comment by Thesola10** [comment]
Graphical fix works, thanks!

**Comment by ChrisLauinger77** [comment]
I took player and widget from the PR and it also still works for me :)
Thx

**Pull request merged**
